import { test, expect, chromium } from "@playwright/test";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TEST_VIDEO_URL = "https://www.youtube.com/watch?v=zfYsSFY4l18&t=51s";

const MOCK_SKILL_DRAFT = {
  skillName: "test-video-skill",
  displayName: "Test Video Skill",
  description: "A skill derived from the test video.",
  triggerGuidance: "Use this when applying the method from the test video.",
  workflow: [
    "Capture the source video context.",
    "Summarize the key steps.",
    "Note limitations from the transcript."
  ],
  importantDetails: ["Source: YouTube video.", "Captions: English (auto-generated)."],
  limitations: ["Skill quality depends on transcript accuracy."],
  videoSummary: "Test video for extension e2e validation.",
  referenceNotes: ["Generated by the YouTube Skill Maker extension."]
};

const MOCK_OPENCODE_RESPONSE = {
  id: "chatcmpl-mock",
  object: "chat.completion",
  created: Math.floor(Date.now() / 1000),
  model: "gpt-5-nano",
  choices: [
    {
      index: 0,
      message: {
        role: "assistant",
        content: JSON.stringify(MOCK_SKILL_DRAFT)
      },
      finish_reason: "stop"
    }
  ],
  usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 }
};

test("captures a real YouTube transcript and generates a skill via the OpenCode Go provider", async () => {
  test.setTimeout(180_000);

  const context = await chromium.connectOverCDP("http://localhost:9222");

  let opencodeRequests = 0;
  await context.route("**/opencode.ai/zen/v1/**", async (route) => {
    const request = route.request();
    if (request.method() === "POST") {
      opencodeRequests += 1;
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(MOCK_OPENCODE_RESPONSE)
      });
      return;
    }
    await route.continue();
  });

  const pages = context.pages();
  const page = pages.length > 0 ? pages[0] : await context.newPage();

  await page.goto(TEST_VIDEO_URL, { waitUntil: "domcontentloaded" });
  await page.waitForLoadState("networkidle", { timeout: 30_000 }).catch(() => {});

  const extensionId = await getExtensionId(context);
  const popupUrl = `chrome-extension://${extensionId}/popup.html`;
  const popup = await context.newPage();
  await popup.goto(popupUrl, { waitUntil: "domcontentloaded" });

  await popup.locator("button:has-text('Make Skill')").click();

  const errorBox = popup.locator("[role='alert']");
  await errorBox.waitFor({ state: "visible", timeout: 90_000 }).catch(() => {});
  const errorText = (await errorBox.textContent().catch(() => "")) || "";
  console.log("popup error text:", errorText);
  console.log("opencode requests intercepted:", opencodeRequests);

  const success = !errorText.toLowerCase().includes("captions were found");
  if (!success) {
    console.log("captions were not captured on real YouTube; transcript capture is still failing");
  } else {
    const preview = popup.locator("textarea").first();
    await preview.waitFor({ state: "visible", timeout: 30_000 }).catch(() => {});
    const draftText = (await preview.inputValue().catch(() => "")) || "";
    console.log("draft skill.md (first 400 chars):", draftText.slice(0, 400));
    expect(draftText.toLowerCase()).toContain("test video skill");
  }

  await context.close();
});

async function getExtensionId(context) {
  for (let attempt = 0; attempt < 30; attempt += 1) {
    const workers = context.serviceWorkers().filter((w) => w.url().startsWith("chrome-extension://"));
    if (workers.length > 0) {
      const url = workers[0].url();
      const match = url.match(/^chrome-extension:\/\/([a-z]+)\//);
      if (match) {
        return match[1];
      }
    }
    const next = await Promise.race([
      context.waitForEvent("serviceworker", { timeout: 2_000 }).then((w) => w).catch(() => null),
      new Promise((resolve) => setTimeout(() => resolve(null), 2_000))
    ]);
    if (next && next.url && next.url().startsWith("chrome-extension://")) {
      const url = next.url();
      const match = url.match(/^chrome-extension:\/\/([a-z]+)\//);
      if (match) {
        return match[1];
      }
    }
  }
  throw new Error("Extension service worker never started.");
}
